name: PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from your repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: mbstring, intl, dom
          tools: composer

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # Step 4: Set up WordPress testing environment
      - name: Set up WordPress Test Framework
        run: |
          wget https://raw.githubusercontent.com/wp-phpunit/wp-phpunit/master/install-wp-tests.sh
          bash install-wp-tests.sh wordpress_test root '' localhost latest

      # Step 5: Run PHPUnit
      - name: Run PHPUnit
        run: vendor/bin/phpunit
